### ISSUE TITLE
自己紹介について

### ISSUE THREAD

**Issue by HoriTokubin** [takaaki-s/developer-magazine-2019#10]
第1章の冒頭で吉川さんが以下のように自己紹介をされています。

『みなさんはじめまして。フリーランスのエンジニアをやっている yskw516 と申します。
AWS をメインとしたクラウドの活⽤コンサルや、オンプレミスからの移⾏プロジェクト
を主にやっています。』

他の章では自己紹介文は無いので、自己紹介をするかしないか揃えた方が良いような気がしました・・・。

**Comment by yskw516** [comment]
すみません、皆さんに合わせる形にしようと思いますので、私の章の冒頭自己紹介は削除しました。
