### ISSUE TITLE
入力ミスと思われる

### ISSUE THREAD

**Issue by HoriTokubin** [takaaki-s/developer-magazine-2019#3]
『2.5 スケーラブルな分散システム』

の中の最新PDFの36ページにて

・『Auto Scaling を設定して負荷状況に応じて自動的ンEC2を増減』
⇒『自動的ン』は入力ミスだと思われます・・・。

・『トラフィックが減ったら EBL から外して EC2 を削除。』
⇒すみません、私が間違っているかもしれません、ELBの間違いではないでしょうか・・・。

**Comment by tomonoriminegishi** [comment]
修正しました。
