### ISSUE TITLE
文章について

### ISSUE THREAD

**Issue by HoriTokubin** [takaaki-s/developer-magazine-2019#5]
最新PDFの9ページの

『開発環境などの 24 時間 365 日稼働が前提ではない環境で意外と見落としがちなコスト削減ポイントを上げていきます。』

⇒
『開発環境などの24 時間 365 日稼働・・・』
の部分が分かりづらいかも・・・

**Comment by tomonoriminegishi** [comment]
文章を全体的に修正しました。
